# Dependabot configuration for repop
# PowerShell project - check GitHub Actions only

version: 2
updates:
  # GitHub Actions (if/when added)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 3
    reviewers:
      - "ChrisClements1987"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(deps)"
